### ISSUE TITLE
Rename executionFlows to codeFlows

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#123]
for the sake of appropriate language.

@michaelcfanning @rtaket FYI

**Comment by michaelcfanning** [comment]
How about using codeFlows instead? In the original design discussions, someone involved pointed out that this data doesn't necessarily represent a path, strictly speaking. This is why we landed on 'executionFlows' rather than 'executionPaths'. Examples include interleaving runtime events in output and merging code execution that occurs on separate threads (for concurrency analysis).

**Comment by ghost** [comment]
@michaelcfanning OK. Updated title of issue to match.
