### ISSUE TITLE
Does some of what's in issue.fullMessage belong in rule metadata?

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#14]
The text currently specifies things like "risks or problems potentially associated with not fixing the problem" and "the full range of responses that an end user could take". That's a lot of information to repeat with every occurrence of an issue in a log file. Should these things go in rule metadata instead of in the issue.fullMessage property?

**Comment by michaelcfanning** [comment]
fullMessage by design provides a comprehensive analysis result that is sufficient to diagnose/resolve an issue. The first sentence of fullMessage, by convention, or optionally the shortMessage provides a concise issue summary. To avoid string duplication in the file, we could populate rules metadata with format strings and reference those in specific issues.

**Comment by ghost** [comment]
@michaelcfanning  Yes, I think that's the right approach. As we've discussed, it puts us in the business of deciding on a string substitution mini-language (C-style, C#-style?). And if we decide, say, on C-style, then implementations in other languages like C# have to interpret it. See #32.

Let's leave as-is for now, and for v2 consider optional extensions for reaching into metadata for messages.

**Comment by ghost** [comment]
This was originally closed as "Won't fix" (although we didn't have that label at the time), but since then, we have in fact implemented this in the Rule Metadata Profile by way of the properties `ruleDescriptor.formatSpecifiers` and `result.formattedMessage`.
