### ISSUE TITLE
'files' needs to be keyed by a string

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#151]
The fragment of a URI is defined to be client-only data and is therefore not considered in equivalence comparisons. Because we require the fragment to be considered for the dictionary of nested files, we need to key this dictionary by string. Or consider some other solution.

**Comment by ghost** [comment]
In JSchema I have a class [UriOrFragment](https://github.com/lgolding/jschema/blob/master/src/Json.Schema/UriOrFragment.cs) that we could use as the key. It's doc comments explain why I wrote it. That reason no longer applies (because `file` objects no longer contain a property that might consist only of a URI fragment), but the class is still around.

**Comment by ghost** [comment]
This was actually an SDK issue. The spec says "each property name in the `files` object shall be the URI of a scanned file", but there's no confusion, because all JSON property names are strings.

And as for the SDK, the CodeGenHints.json file now correctly gives a plain dictionary hint for `Run.Files` -- that is, it does not specify a `KeyTypeName` -- and the generated file correctly declares `Run.Files` as `IDictionary<string, IList<FileData>>`, so there's nothing more to do.
