### ISSUE TITLE
Provide guidance on "minimal" fixes

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#224]
@michaelcfanning Writes:

> A subtlety for the spec, to maximize the ability of tools to provide fixes, they should be careful to make minimal changes to a file. For example, I inject quotes for an unquoted attribute value with two replacements, rather than replacing the unquoted attribute value with a quoted version. By doing this, I preserve the ability to modify the literal contents of the attribute in an additional change.

**Comment by ghost** [comment]
@michaelcfanning Let me make sure I understand the scenario. Suppose a fix wants to change this code:

```
<a b=c />
```

... to this:

```
<a b="c" />
```

You're suggesting the `fix` object (actually the `fileChange` object, since a `fix` can change multiple files) contain two `replacement` objects.
1. Insert `"` at character offset 5.
2. Insert `"` at character offset 6 (which is actually now offset 7)

Now when you say you want to "preserve the ability to modify the literal contents of the attribute in an _additional change_ [my emphasis]", do you mean "... in an additional `replacement` object within the same `fileChange` object"? Because of course you could do that anyway:
1. At offset 6, remove 1 character (the `b`) and insert 2 characters (say, `qq`).

Or, if this were part of a single fix, you could do it in one fell swoop:
1. At offset 5, remove 1 character (the `b`) and insert 4 characters (say, `"qq"`).

So I conclude you must be referring to a scenario where the quotes are added, and then the some _other_ fix is applied.

A system that applies fixes has to keep track of the bytes added and removed  by each fix. Is your concern that such a system, upon noticing that fix #1 has _replaced_ the bytes that fix #2 would have modified, decides not to apply fix #2? Whereas, if fix #1 had carefully inserted bytes _on either side of_ the range that fix #2 wants to modify, then the system would have agreed to apply fix #2?

**Comment by michaelcfanning** [comment]
I think you've got it. Imagine in addition to the 'encapsulate all attribute values with quotes' rule, there is a second rule, 'change all "b" attribute values of "c" to value "d"'. If a fixer has replaced c with "c" instead of merely inserting the quotes, then that fix has replaced the target of a follow-on check (which can't be applied).

This comment is based on the observation of the most convenient way to apply multiple fixes. One approach is to interleave all requested changes (by sorting them in order of the offset where the change occurs). As long as the target regions don't overlap, the set of changes can be applied in order of increasing offset.

**Comment by ghost** [comment]
OK, thanks, I have enough to write the words now.
