### ISSUE TITLE
Is there a reason to recommend upper-casing?

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#231]
Annex D (Determinism) recommends choosing upper-case when performing a case-insensitive comparison on the .NET platform. Is there security-driven reason for this that applies to expected SARIF usage scenarios? If not, we should remove this language.

@michaelcfanning @nguerrera FYI

**Comment by nguerrera** [comment]
See https://msdn.microsoft.com/en-us/library/ms973919.aspx

AFAIK (cc @ellismg to set me straight), it is more of a Windows consideration than a .NET consideration. The same guidance applies to unmanaged code on Windows. The correct and secure way to compare case-insensitive Windows identifiers (e.g. user names, file names, etc.) is:
- **.NET**: `String.Compare(x, y, StringComparison.OrdinalIngoreCase)`
- **Win32**: `CompareStringOrdinal(x, xCount, y, yCount, /*bIgnoreCase*/TRUE)`

These are functionally equivalent to `x.ToUpperInvariant() == y.ToUpperInvariant()`, but not `x.ToLowerInvariant() == y.ToLowerInvariant(`). Thus, if you decide to normalize casing, you should use ToUpperInvariant() so that it will continue to be ordinal-ignore-case-equal to the same set of strings after normalization.

**Comment by nguerrera** [comment]
I don't understand the relationship between 03cb63a and this issue.

**Comment by ghost** [comment]
@michaelcfanning @nguerrera Sorry, I closed the wrong issue.

**Comment by nguerrera** [comment]
I think in the interest of being cross-platform, it is best to just leave paths alone. Either use the casing that is supplied by the user/invocation or the preserved casing returned from the file system. This does not (in my opinion) mean non-determinism as the log will only change when the invocation or file system entries change.

**Comment by ghost** [comment]
Yes. I see. If tonight's build uses a new version of a tool, which emits lower-case names, while the version I ran last night emitted upper-case names, then it's perfectly fine to consider the log file has changed -- or at least, it's not worth the trouble to try to convince ourselves that it _hasn't_ changed. Similarly, if tonight's build invokes the tool with a different set of command line options, so that file names are emitted in a different case, it's acceptable to consider the log as having changed.

By this reasoning, we should omit the whole spec section on [Case-insensitive file format elements](https://rawgit.com/sarif-standard/sarif-spec/master/Static%20Analysis%20Results%20Interchange%20Format%20%28SARIF%29.html#annex-e-case). Do you agree?

**Comment by nguerrera** [comment]
Yes, I agree.

**Comment by michaelcfanning** [comment]
Wait, what about the build caching scenario? Consider a follow-on task that files active bugs but should only be invoked when the log file has changed. What if an infrastructure owner would like to prevent that task from waking up on every build, because two different VMs happen to emit paths with different casing. There are two ways to handle this, provide for intelligent diffing after log production or make sure the log production is deterministic for a more naïve diffing approach. I don't think we can bail completely on this latter scenario (even if we believe it should be avoided, a position that I do agree with).

**Comment by nguerrera** [comment]
Why are two different VMs doing that? That is the root of the problem IMHO. The file system and all major source control systems are case preserving.

**Comment by ghost** [comment]
Yes, this whole discussion is about the caching scenario (that's why we care about determinism). My position was that, in the two scenarios Nick imagined (1. New version of tool emits different casing, 2. Same tool with different command line emits different casing), it's not worth doing the extra work to decide if these two naively different files are logically the same.

You're proposing a third scenario: the build behaves differently on two different VMs. That's just bad news. The build engineers should fix it. I don't think we need to write spec text to accommodate it.

**Comment by ghost** [comment]
@nguerrera @michaelcfanning Are we agreed with Nick's proposal to leave casing alone (and my proposal to remove the [relevant section](https://rawgit.com/sarif-standard/sarif-spec/master/Static%20Analysis%20Results%20Interchange%20Format%20%28SARIF%29.html#annex-e-case) from the spec)?

**Comment by michaelcfanning** [comment]
I do not agree. What I'm uncomfortable with here is that your position is prescriptive, as far as use of the format. If we get to a place where we say, the bug is in your VM mgmt., you can't fix this in the format, that makes me uncomfortable. Instead, our job is to note the engineering advantages/disadvantages implied by casing variance  for case-insensitive things (just as we started to do). It is perfectly fine for a VM mgmt. team to propose to solve this problem by normalizing all casing in SARIF output. If there is a need, they should use the comparison conventions of the OS, as Nick says. In many cases, there might not be a relevant security problem that prompts this, and they can propose whatever is most readable.

**Comment by nguerrera** [comment]
If we're keeping a section, I don't agree with the wording: "Case-insensitive file systems can also cause non-deterministic output." This is not true unless the file system is also not case-preserving, which is not the case on any modern system. If casing is left alone, the casing in the log will either be 1) what was passed to the tool or 2) what was returned as the file name from the OS. Source control systems also preserve case. Neither of these change randomly. Something explicit (file rename, or changes to invoking script) had to happen. I fail to see what that has to do with VM management.

Even with /deterministic, csc will preserve casing of document paths in PDBs. I maintain this is the right choice and if someone were to have a build that changed document casing between runs, I would absolutely push back on hacking around it in the compiler. There is something checked in to their source tree causing it. I don't see how SARIF should be different.

**Comment by ghost** [comment]
(@nguerrera In the next sentence I do specify that we're talking about "case-insensitive but case-preserving" file systems. If we keep this section I'll clean this up.)

**Comment by ghost** [comment]
@nguerrera Michael is concerned with the case where different VMs have different versions of the tool, which emit file URIs with different casings, or different build scripts, which invoke the tool with different command lines and as a result produce different casings.

**Comment by ghost** [comment]
My position was "fix it", and Michael's answer was "What if they can't or don't want to? Why shouldn't we give them the option to paper over the problem in SARIF?"

**Comment by nguerrera** [comment]
Just to be clear about earlier comment, I'm pushing back on the notion that such file systems cause "non-determinism". It seems like we're after something more than determinism, which is to make the output invariant to file name casing changes (in invocation or on disk).

**Comment by nguerrera** [comment]
Eliminating differences between tool versions should be a non-goal. Static analysis has always been sensitive to tool upgrades. Plus, we write the tool version in the log!

**Comment by ghost** [comment]
Ah, good point, we write the command line in the log too. So in each of the scenarios we've identified, the logs would differ even if the casing of all the file URIs were uniform.

**Comment by michaelcfanning** [comment]
We have information in the log elsewhere that documents format elements that are very likely subject to non-determinism. Producers have the choice not to emit that data. I'll reduce this argument again to two positions: some systems will want to perform unintelligent diffing (log files must be byte-per-byte identical. invariant on disk run-over-run as Nick usefully framed it). other systems will perform weak/intelligent diffing. It is not our place to prescribe what approach to take. Our job is to provide useful information that may be relevant to each scenario.

**Comment by nguerrera** [comment]
I am arguing that preserving input casing of file names is perfectly sufficient for run-over-run, unintelligent diffing. The only time there will be a difference between runs is if the invocation changes or the file name changes. Otherwise, two subsequent runs will not differ by case alone.

The more I think about it, the more strongly I think that we should actively discourage any file name case normalization. I think that SARIF producers should behave as all modern file systems do and always _preserve case_. If the _producer_ normalizes, it is actually asserting something about underlying file system of the _consumer_!

Example:
- Producer runs on Windows box using NTFS and decides to lower-case the file names in the log.
- Source files and sarif log are transferred to a Linux box using ext4.
- Log file has paths that do not work on the destination system

Note that this example has nothing to do with upper vs. lower (or choice of casing table), it's just that changing case at all is bad for interop.

**Comment by michaelcfanning** [comment]
I believe I am persuaded. What's sunk in only as of your last comment is that we are really only addressing the issue of file name case normalization, as you say. My argument re: VMs was weak because it should be possible to configure these environments to reproduce a canonical, non-arbitrary casing (e.g., derived from the source control system). This means that invariance when persisted to disk should be possible (and not burdensome). So, Larry's summary stands: failure to do so is a bug (which should be straightforward to fix).

OK. I'm convinced. Thanks to you and @lgolding for your tenacity on this.

**Comment by ghost** [comment]
Good discussion, all. Ok, I will remove the section on case normalization.
