### ISSUE TITLE
Should there be additional structure for annotating codeFlowEntry objects?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#25]
Currently, a string 'message' property is associated with annotatedCodeLocation objects. The contents of this message is unspecified, due to variance in tooling as far as annotating code paths/data values/analysis assumptions during analysis. Should we consider adding more formal mechanisms for expressing some of these things?

Arguing against: this problem is relevant to a subset of tools covered by Sarif. It is not clear that there is sufficient commonality between sophisticated checkers that produce this sort of analysis metadata to warrant/benefit from a std scheme.

**Comment by ghost** [comment]
@michaelcfanning is working on a viewer to show annotated code locations, which could surface more requirements on the annotatedCodeLocation object. Nothing for now.

**Comment by ghost** [comment]
The output of the Static Driver Verifier tool labels each step in a code flow with a "kind" value such as "Call", "Return", and "Assignment". We should consider adding a `kind` property to `annotatedCodeLocation`. That is especially useful for viewers because they could present the list of locations as a tree view. For example, if A calls B, B performs an assignment, B returns to A, A calls C, and C performs an assignment, the viewer could rended this sequence of `annotatedCodeLocations` as:

```
A
    call B
        assignment
        return to A
    call C
        assignment
```

That actually only makes sense when the `annotatedCodeLocations` are part of a `codeFlow`. When they're part of a `stack`, `kind` isn't needed because they're all calls.

**Comment by ghost** [comment]
Add `annotatedCodeLocation.kind`. Collect the set from PREfast "key events" + the ones SDV uses.

**Comment by michaelcfanning** [comment]
declaration : declaration of item
branchTrue : conditional/comparison evaluated to true at location
branchFalse : evaluated to false
use : use of item
call : call begins
callReturn : call returns
functionEnter : function entered
functionExit : location of function exit
source : the source of untrusted input driving analysis
sink : a sink of interest 
sanitize : the location of a sanitization step that removes taint from data

**Comment by ghost** [comment]
We've settled  on the list of `kind` values, added an `id` property (standing in for "`step`"), and added several more properties (`module`, `threadId`, `essential`, FQLN, `logicalLocationKey`), and all of it is documented. This is done for v1.

@michaelcfanning FYI
