### ISSUE TITLE
Unclear why hashes property in fileReference is an array

### ISSUE THREAD

**Issue by zlandau** [sarif-standard/sarif-spec#27]
The fileReference object has a uri that seems to specify a single file. But the hashes property allows multiple hashes. It's unclear to me why this is necessary. Are there cases where multiple hash algorithms would be used in a single run?

**Comment by michaelcfanning** [comment]
@zlandau, in general, probably not, providing multiple hashes would be more common for security scenarios (where you might be tracing binaries across multiple data stores). @lgolding, where have we landed on permitting properties to hold either an array or a single instance of an item (if there is only one)?

**Comment by ghost** [comment]
Allowing a single property to have either a scalar or an array value would make it awkward to represent the contents of the file as an object (because what would be the type of that property?) and would make it harder for a JSON library to deserialize.

What do you think of allowing defining both a `hash` property and a `hashes` property, and specifying the constraint that they can't both be present? and we apply the same approach anywhere in the spec where a property can be either scalar or array, but the scalar value is by far the most common?

**Comment by zlandau** [comment]
That sounds reasonable. Alternatively, having only the array but describing why in the documentation is an okay fallback. The problem is mostly when you see the documentation specifying an array but most people can only think of a single value that would go in there.

**Comment by ghost** [comment]
Thanks Zachary. In that case, since we are attempting to lock down v1 of the format as quickly as possible, and since it would be a non-breaking changes to add a scalar `hash` property in future, and since you are open to the idea of keeping the current design, as long as it's properly documented, I propose to do exactly that. I'll send a pull request with the change.
