### ISSUE TITLE
What format should formatSpecifiers use

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#32]
We say that a `formatSpecifiers` value "shall be a string that can be passed as a control parameter to string formatting API (e.g., `printf`)," and then we give an example in `printf` format. As soon as we get into the "formatted string" business, we have to commit to a substitution syntax, or else the format won't be interoperable with all tools that might consume it. Do we use %s  like  printf ?  {0}  like C#? Something else?

**Comment by ghost** [comment]
Possibility: formatSpecifiers is a dictionary keyed by language (C, C#), whose elements are the current "name: formattedString" pairs. The schema constrains the languages that can appear. Research the appropriate set of lang identifiers.

**Comment by michaelcfanning** [comment]
We have some important considerations for our scenario. First, SARIF produces must convert all arguments to strings. This implies that locale-specific formatting (such as a date or currency values) must already be applied. As a result, we should pick a conversion specifier option that is limited to the string type. There's no pressure to support other options, length, precision, etc. since these can be reasonably applied when producing the string argument. 

As far as existing conventions, there are at least three options to consider. (thanks @bion for input and pointers): 1) mustache logicless templates, 2) the c/c++ printf standard, 3) .net string.format convention

http://mustache.github.io/mustache.5.html. An issue with the mustache mechanism is that it would introduce additional complexity to rendering: arguments would become a JSON object and argument names would need to be authored.

https://www.gnu.org/software/libc/manual/html_node/Output-Conversion-Syntax.html
% [ param-no $] flags width [ . precision ] type conversion
For C/C++ (and Java), a convention that meets criteria above would be to allow for string arguments to be referred to by position, e.g., %1$s, %2$s, etc.

https://msdn.microsoft.com/en-us/library/dwhawy9k(v=vs.110).aspx
The .NET convention has some appeal due to its simplicity, for example, the string type does not need to be expressed. Following this convention, we would specify {0}, {1}, {2}, ... {n} to refer to arguments in the arguments array. We would not permit additional any conversion options. Braces would be escaped by doubling them, {{ and }}.

I suggest we proceed with the last option. Bill went through an exercise of writing a C++ parser for this convention and didn't find it burdensome (we can publish this code in an appendix or separate doc, along with language-specific details on producing the supported date format).

**Comment by ghost** [comment]
I see. Your argument hinges on the fact that the members of the `formattedMessage.arguments` array are in fact already specified to be strings, so all message-element-to-string formatting has already happened by the time the SARIF file is produced:

```
results: [
  {
    "formattedMessage": {
      "specifierId": "salesPitch",
      "arguments": [ "4", "49.99" ]
    }
]
```

I'm ok with that. There's another option for the replacement tag syntax though: a simple `%n` or `$n`, with the tag-start character escaped by doubling:

```
Yours for $1 easy payments of $$2!
```

... and of course we'd need to specify whether replacement numbers are 0-based or 1-based.

**Comment by michaelcfanning** [comment]
Advantages: simple, new (in the sense that we're not biasing ourselves for any specific lang/plat/etc)
Disadvantages: every SDK consumer needs to author a helper (but costs should not be high)

**Comment by ghost** [comment]
Could you explain what you mean by a "helper"? Naively, I'd think that anything "every SDK consumer needs to author" could itself be part of the SDK.

**Comment by ghost** [comment]
And it's never as simple as that, of course. In my proposal, if the substitution tag is immediately followed by a number, you can't tell if `$11` means "tag #1 followed by a literal '1'" or "tag #11". So you have to allow `${1}1`, and then you might as well just use C#-like `{n}`. So I withdraw my suggestion.

**Comment by ghost** [comment]
... and I'm ok with settling on C#-like `{n}`.

**Comment by michaelcfanning** [comment]
Yes, you're right, too bad, it was an attractive idea. :) Yes, let's go ahead and proceed with {0}...{n}.
