### ISSUE TITLE
standardize issue kind?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#34]
This relates to a long-standing discussion. We do not have a standard way to bucket issues in a SARIF log in a way that groups issues by required action. An issue that reports a tool internal error, for example, should be denoted (because it should not be suppressible, needs to be routed to a tool owner rather than code owner, etc.). The log file could also provide a mechanism to emit information that is supports other diagnostics (a 'note' in Clang terms). For compliance/auditing scenarios, it would be useful for issues to provide a 'pass' designation. Below is a proposal for grouping checks:

1) error
2) warning (we support these two severities due to prevalence in existing tools)
3) internal error (should not be suppressible)
4) log msg or 'note' (should have a 'relatesTo' field, so that groups of related messages can be preserved when sorting)
5) 'not applicable' (a useful designation when an analysis target is altogether invalid for analysis
6) 'pending' or 'observation' (this one's fuzzy but the idea is to emit output which can't be evaluated as pass/fail without post-processing/application of policy.

**Comment by michaelcfanning** [comment]
@lgolding @nguerrera from SDK testing, we should close on this addition.

**Comment by michaelcfanning** [comment]
Suggest starting with 'pass', 'error', 'warning', 'internalError', 'note', 'notApplicable' immediately.

**Comment by nguerrera** [comment]
That works for me, with those being possible values of "kind" key on issue object.

**Comment by ghost** [comment]
I don't think "pass" belongs in this set of values. The SARIF log by design contains "issues" detected by tools. If the tool detects that a particular analysis target doesn't violate a particular rule, it doesn't emit a "pass" issue into the log, it simply refrains from writing anything into the log.

I don't understand the rationale for a "note" issue kind. What's an example? What exactly would the "relatesTo" field contain?

"Not applicable" - is this for when you run a C#-specific rule against a C++ target? Is that what you meant by "invalid for analysis"?

I'm uncomfortable with the "error/warning" classification. We relegated "severity" to the property bag because we couldn't agree on a classification. Are you proposing to adopt this classification now? I agree those two classifications are widely used. Will we allow tools that support a finer-grained classification to use the "kind" field for that?

**Comment by michaelcfanning** [comment]
'pass' is definitely a valid static analysis result. I see your point about the term 'issues' so perhaps we should change this term to 'results'. 'Results' after all is right there in the name SARIF. issueLog would be resultsLog, etc.

A note is used for logging useful messages, which might or might not be attached to a prior issue. A note might inform the user that a rule was disabled entirely for a file due to encountering a #pragma in source. We should cover (relatedTo in a separate issue)

Yes, 'notApplicable' indicates that a check was not valid for an analysis target that was passed to it. That is, there is no way for the target to provoke the problem/condition which a check enforces. 

Yes, I am essentially proposing that we take the 'fail' condition and break it into two levels, error and warning. Any more detailed severity is still relegated to the property bag.

btw - in the event that result 'kind' is not present, we need to suggest a default value for viewers (probably 'warning')

**Comment by ghost** [comment]
@michaelcfanning and I came up with an alternative to having `issue` objects represent all the kinds of information you discussed in #34, “Standardize issue kind”. Some of the kinds you mentioned, such as Error and Warning, would indeed be covered by adding an ``issue.kind` property. Other kinds of information would be represented by “notes”. Notes that relate to individual issues would be attached to the `issue` object; other notes would be attached to the `issueLog`.

Michael and I are still wrestling with some details, but I’ll put out a PR with what we have.
