### ISSUE TITLE
Not all analysis tools work on files

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#4]
Jeffrey van Gogh suggested:

Section 4.9.5: not all analysis tools work on files. Remove the restriction that the analysis target is a file; allow it to be any URI (this applies to all places where "physical file" or the like is mentioned).

**Comment by michaelcfanning** [comment]
yes. 'physicalLocationComponents' consists of uri + mime-type and a region, so that's right. the doc describes the possibility of this being a file but doesn't require it. we should update 4.9.5 to remove the language around file, as jeff says. rather than 'the file that the static analysis tool', prefer 'the item' or something else.

**Comment by ghost** [comment]
We addressed this by adding a definition for "file" to the Terms and definitions section of the spec. The definition says that a file is any sequence of bytes that you can address by a URL. Now every place we refer to "file" in the spec, it has this broader meaning.
