### ISSUE TITLE
Consider adding consumer/producer to each "profile"

### ISSUE THREAD

**Issue by ghost** [sarif-standard/sarif-spec#48]
See @codecurmudgeon's comment on #29, "Organizing SARIF into code format + profiles" for context.

**Comment by ghost** [comment]
@michaelcfanning @codecurmudgeon

The documentation for each profile starts with an explanation of the scenario the profile is intended to address. For example, the [Tool Orchestration Profile](https://rawgit.com/sarif-standard/sarif-spec/master/Static%20Analysis%20Results%20Interchange%20Format%20%28SARIF%29.html#tool-orchestration-profile) section starts:

> It is often desirable to integrate the results produced by a static analysis tool into a larger process that orchestrates the operation of several tools. For example, static analysis might be part of a nightly build process that combines build tools, test tools, and deployment tools.
> 
> The Tool Orchestration Profile defines additional optional elements of the SARIF format that are intended for use in this scenario.

Does this meet our needs? Or are you looking for something more explicit?

**Comment by michaelcfanning** [comment]
I believe the driver for this issue was based on the observation that it may be useful to separate profiles into special sections for guidance on production vs. consumption. We have special guidance if you are authoring a converter, for example. On the other hand, if you intend to consume the output of SARIF converters, we might have other guidance. Just a thought on how to organize. e.g., we could have a general section, then 'special notes for consumers', 'special notes for producers'. Not actually proposing those section names, btw.

**Comment by ghost** [comment]
Hmm. That idea applies as well to the core format as it does to the profiles. Let me think about it. In the meantime, changed label from "non-breaking" to "documentation-only".

**Comment by ghost** [comment]
@michaelcfanning Closing this since we've eliminated the notion of "profiles" altogether.
