### ISSUE TITLE
'analysisTarget' should probably be optional

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#65]
Consider the converter scenario. For some tools, it might not be possible to know what the original analysis target was (an analysis against a C++ file might produce a result against an included .h file, for example). For this case, it is reasonable for the tool converter to use `issueFile` exclusively for converted results. Currently, our spec requires `analysisTarget` to exist. So, the converter is required to express this member and leave it null.

I wonder whether it wouldn't be cleaner for us to reverse things a bit. i.e., we should require `issueFile` and, in the event a direct SARIF producer happens to know the `issueFile` differs from the original analysis target, they could provide an optional `analysisTarget member`. What do you think, @lgolding?

This will cause churn in current SARIF implementers so would be good to close asap.

**Comment by ghost** [comment]
It is a good point: a tool that converts log files from some other tool into SARIF format might not know the "analysis target." For example, if the original log file just says "error C1234 on line 10 of file header.h", the converter has no way to know whether the tool was instructed to scan header.h (in which case header.h would be the analysis target), or whether the tool was instructed to scan source.c, which included header.h (in which case source.c would be the analysis target and header.h would be the issue file).

In this scenario, the only thing the converter knows for sure is that an issue _was_ found in header.h, so the best it can do is to set `issueFile` to header.h and leave `analysisTarget` blank.

So far I agree with you. But I'm really struggling with the idea of making `analysisTarget` optional for tools that actually perform analysis, because it's so useful to know all the results you get from scanning source.c.

We discussed the possibility of saying something like this: "Any tool that knows the `analysisTarget` must supply it, and it must omit `issueFile` unless it's different from `analysisTarget`. A tool that knows only the `issueFile` must supply it, and it must omit `analysisTarget`".

Do you think that's too confusing?

**Comment by michaelcfanning** [comment]
I don't think it's confusing at all, this is a perfectly reasonable counter-proposal. I support it. I've taken a good look at various converters and there's a mix of situations. An FxCop project file, for example, clearly denotes its analysis targets. Other tool output files do not make this clear (but in some cases, knowledge of the tool can allow a converter to do the right thing).

In any case, I like your proposal.
