### ISSUE TITLE
Should physical locations have optional hash values?

### ISSUE THREAD

**Issue by amcasey** [sarif-standard/sarif-spec#81]
It looks like `fileReference` objects can have hash values, but I don't see a corresponding member on `physicalLocationComponent`.  It seems like that would be useful for determining whether the file had change since the SARIF file was produced.

On a related note, should there be some way to refer to `fileReference` objects from `physicalLocationComponent` objects?  They seem likely to be related, but I don't see a way to pair them up.

**Comment by amcasey** [comment]
FYI @lgolding

**Comment by ghost** [comment]
@amcasey  Hi Andrew,

`physicalLocationComponent` has a `uri`, which should (see disclaimer below) match the `uri` of one of the `fileReference` objects in the `runInfo.analysisTargets` array. That's how you would pair them up (unless I'm misunderstanding you).

Once you can match a `physicalLocationComponent` object with a `fileReference` object, you don't need to repeat the values from `fileReference.hashes` in the `physicalLocationComponent`.

Disclaimer: The spec states that `runInfo.analysisTargets` represents the set of "analysis targets scanned during the run", and it defines an analysis target as a "programming artifact which a static analysis tool is instructed to analyze". So if you run

```
lint a.c b.c c.c
```

then `analysisTargets` should contain exactly those three files. Now what happens when lint discovers an issue in `d.h` which is included by `a.c`? The spec says that `d.h` is the "`resultFile`" (the file where lint found the issue), as opposed to `a.c`, which is the "`analysisTarget`" (the file that lint was instructed to scan). `d.h` isn't mentioned in `runInfo.analysisTargets`, so you don't get a hash value for it.

@michaelcfanning, any thoughts on this? Do we want to add optional hash values to `physicalLocationComponent` to deal with this scenario?

**Comment by amcasey** [comment]
@lgolding When I mentioned pairing them up, I was thinking of something like an index into the `analysisTargets` array.  Would that be too fragile?

**Comment by ghost** [comment]
@amcasey Are you suggesting that we could add an integer property `physicalLocationComponent.analysisTargetIndex`, which would index into the `ruleInfo.analysisTargetsArray`?

**Comment by ghost** [comment]
@amcasey ... in addition to the existing `physicalLocationComponent.uri`?

**Comment by amcasey** [comment]
@lgolding I've never actually consumed a SARIF file, but that seems like something I might want if I were to do so.  Mostly, I wanted to make sure someone had thought about it.

Without an index, I think you'd have to build a URL-to-hash dictionary, correct?

**Comment by ghost** [comment]
@amcasey Yes, that's exactly right. Let me suggest this: we are working on closing down the SARIF spec, and we're trying to avoid adding anything that doesn't have a clear use case. I suggest we close this, with the understanding that we can always revisit it if a clear use case emerges. Is that OK?

@michaelcfanning FYI -- but please consider the issue I raised above, which is whether we need to address the issue that result files that are not mentioned in analysisTargets won't have hash values available.

**Comment by amcasey** [comment]
@lgolding  As long as any physical location can have a hash, I'm satisfied.

**Comment by ghost** [comment]
@amcasey @michaelcfanning We now have a design that will enable you to obtain the hash for any physical location. It will be done _via_ a dictionary lookup on the URL, not by a numeric index. The spec will be clarified to allow file references (and therefore hashes) to exist for all files in which results are found.

@amcasey Note that hash is optional. There's no guarantee that every tool will populate it.
