### ISSUE TITLE
Use "CharInLine" rather than "Column" for locations

### ISSUE THREAD

**Issue by ScottLouvau** [sarif-standard/sarif-spec#83]
In VS terms, "Column" (as in PhysicalLocation.StartColumn" means the visual column. If you have a tab on the line, it'll be one character but [TabSize] columns. You probably don't want analysis tools worrying about how wide tabs are, and you want to make it clear that you'll ask to navigate to the character, not the column.

**Comment by ghost** [comment]
@michaelcfanning Per our discussion just now, we should accept this change, for exactly the reason Scott and you cite. Honk if you agree (or just set triage-accepted and remove discussion-ongoing).

**Comment by ghost** [comment]
And per further discussion, we will not accept this change, because we can't think of a clear term for the concept. We will continue to use `column`, but will document that this refers to a 1-based count of characters from the start of the line, and that in the presence of tabs, viewers will need to adjust the visual column accordingly.

So this is no longer a breaking change, it's documentation-only.

**Comment by ghost** [comment]
Restored the original labeling. This would have been a breaking change, we're not going to do that, and #125 tracks the documentation change we _are_ going to make.
