### ISSUE TITLE
Should we reintroduce a tags member?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#87]
We previously defined a tags member for results that was designed to be a set of strings associated with a result. We attempted to simplify this design by noting that SARIF producers could purpose the properties member for this scenario (providing a key associated with an empty value). We notice that producers are tempted to create a 'tags' property with a value that consists of a set of tags delimited by some character such as a semicolon or comma. 

Minimally, the spec should address this scenario. Producers will arguably be more likely to find/use the correct tag mechanism if were reintroduce the property.

**Comment by ghost** [comment]
I see. You're saying that, in the common case where a tool vendor already has a notion of "tags" in their native format, they do _not_ naturally decide to emulate the tags with a property bag where the keys are the tags and the values are empty:

```
properties: {
    "firstTag": "",
    "secondTag": "",

    "someOtherProperty": "val"
}
```

Instead, they tend to invent a mini-language within an individual property:

```
properties: {
    "tags": "firstTag;secondTag",

    "someOtherProperty": "val"
}
```

... and that means consumers have to know how to parse it. Whereas, if we defined `tags` ourselves, they would naturally discover and use it:

```
tags: [
    "firstTag",
    "secondTag"
],
properties: {
    "someOtherProperty": "val"
}
```

... otherwise known as "falling into the pit of success".

Is that your argument? If so, I agree with it.

**Comment by michaelcfanning** [comment]
Yes! Precisely. :)

**Comment by ghost** [comment]
OK, I will update the spec. This is not a breaking change.
