### ISSUE TITLE
Should we specify a standard behavior for missing required data when converting?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#95]
SARIF is designed to accommodate conversion from existing analysis tool formats. In some tools, under some circumstances, data that is specified as required by the SARIF spec may be missing. As an example, 'ruleId' is currently a required member but an analysis tool may not have bothered to specify an identifier to organize tool output. 

In these cases, a converter author might attempt to contrive an identifier from other data (but would do so without guidance from this spec). Alternately, we could specify a standard value for any missing required data. This would allow SARIF consumers to determine when information was absent in the original log (pushing decisions on how to accommodate to the consumer as opposed to the converter).

@lgolding @nguerrera and others, any thoughts on this topic?

**Comment by michaelcfanning** [comment]
Note that we should consider two possibilities: 1) if a log file reasonably does not contain data SARIF requires, 2) if a log file is simply in an unexpected/possibly corrupted condition. having a Farnsworthian 'eh-WHAAA?' indicator of this condition could be useful.

**Comment by ghost** [comment]
Re: "unexpected/corrupted log file": A converter is under no obligation to produce valid SARIF for a corrupted input file. It can simple exit with an error message.

Re: "missing data": The only case we currently know of is `ruleId`. We will update the spec to say that `ruleId` is "should" instead of "shall", we'll explain when it might not be available, and we'll say what to do if you need to link to a `ruleInfo`.

But I'll wait until Michael has examined some more converter output to settle on this approach.

**Comment by ghost** [comment]
@michaelcfanning This is now resolved by the guidance in Annex C, "Production of SARIF by conversion tools" -- or at list it will be once you sign off on #113.

**Comment by ghost** [comment]
Fixed by 21fca7c and eae67ce.
